# Generated by Django 3.1.1 on 2022-05-16 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefwikiprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chefwikiprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
